import { getLanguage } from './qgcs4PreviewModel.js'

export const UI_COPY = {
  report: ['选手技术分析报告', 'Player performance report', '선수 경기력 분석'],
  reportAccess: ['俱乐部技术报告', 'Club scouting report', '클럽 스카우팅 보고서'],
  dataAsOf: ['数据截至', 'Data as of', '데이터 기준일'],
  poolBadge: ['完整池 {n} 人', '{n} eligible peers', '비교 대상 {n}명'],
  runnerUp: ['次位候选', 'Next candidate', '다음 후보'],
  orderFixed: ['当前候选顺序', 'Current candidate order', '현재 후보 순서'],
  positionRecord: ['本位置记录', 'Position record', '포지션 기록'],
  playerSnapshot: ['选手概览', 'Player snapshot', '선수 개요'],
  decisionBriefEyebrow: ['经理决策摘要', 'Manager decision brief', '매니저 의사결정 요약'],
  decisionBriefTitle: ['30 秒读懂 {name}', '{name} in 30 seconds', '30초 안에 보는 {name}'],
  currentTechnicalPosition: ['当前技术位置', 'Current technical position', '현재 기술 위치'],
  decisionScale: ['同位置指数：50 为中位参考，越高越靠前。', 'Within-position index: 50 is the median reference; higher ranks farther forward.', '동일 포지션 지수: 50은 중앙값이며 높을수록 상위입니다.'],
  decisionBand_LEADING: ['领先区', 'Leading', '선두 구간'],
  decisionBand_STRONG: ['前段区', 'Strong', '상위 구간'],
  decisionBand_ABOVE: ['中上区', 'Above median', '중상위 구간'],
  decisionBand_MIDDLE: ['中位区', 'Middle band', '중간 구간'],
  decisionBand_WATCH: ['观察区', 'Watch band', '관찰 구간'],
  briefFactor_profileFloor: ['竞技下限', 'Competitive floor', '경기 하한'],
  briefFactor_consistency: ['稳定兑现', 'Consistent delivery', '안정적 수행'],
  briefFactor_versatility: ['英雄池覆盖', 'Hero-pool coverage', '영웅 폭'],
  briefFactorMeta_profileFloor: ['较差地图仍能保留的相对水平', 'Relative level retained on weaker maps', '부진한 맵에서도 유지한 상대 수준'],
  briefFactorMeta_consistency: ['地图之间的波动控制', 'Control of map-to-map variation', '맵 사이 경기력 변동 제어'],
  briefFactorMeta_versatility: ['本届记录中的英雄分布', 'Hero distribution recorded in this event', '이번 대회에 기록된 영웅 분포'],
  dossiers: ['选手档案', 'Player dossiers', '선수 분석'],
  compareShort: ['候选对比', 'Compare', '후보 비교'],
  rankPressure: ['顺位压力', 'Rank pressure', '순위 압박'],
  selectionDecision: ['选拔判断', 'Selection decision', '선발 판단'],
  deploymentFit: ['部署适配', 'Deployment fit', '기용 적합도'],
  evidenceCheck: ['证据核验', 'Evidence review', '근거 검토'],
  methodShort: ['模型方法', 'Model & method', '모델·방법'],
  previousPlayer: ['上一位候选', 'Previous candidate', '이전 후보'],
  nextPlayer: ['下一位候选', 'Next candidate', '다음 후보'],
  compareMinimum: ['至少保留 2 人；先添加一位，再移除当前候选。', 'Keep at least two candidates. Add another before removing this one.', '후보를 최소 2명 유지합니다. 다른 후보를 추가한 뒤 해제하세요.'],
  compareMaximum: ['最多同时对比 3 人；先移除一位，再添加新候选。', 'Compare up to three candidates. Remove one before adding another.', '최대 3명까지 비교합니다. 한 명을 해제한 뒤 추가하세요.'],
  overviewBar_overall: ['条形：技术指数 · /100', 'Bars: technical index · /100', '막대: 기술 지수 · /100'],
  overviewBar_consistency: ['条形：发挥稳定性指数 · /100', 'Bars: consistency index · /100', '막대: 일관성 지수 · /100'],
  overviewBar_pressure: ['条形：强敌校正表现 · /100；— 为样本不足', 'Bars: adjusted stronger-opponent performance · /100; — means insufficient evidence', '막대: 강한 상대 보정 경기력 · /100; —는 표본 부족'],
  overviewBar_heroes: ['条形：英雄覆盖指数 · /100', 'Bars: hero-coverage index · /100', '막대: 영웅 활용 범위 지수 · /100'],
  event: ['全高杯 S4', 'Quangao Cup S4', 'Quangao Cup S4'],
  preview: ['本地预览', 'Local preview', '로컬 미리보기'],
  overview: ['五位置总览', 'All positions', '포지션 개요'],
  skip: ['跳转到报告正文', 'Skip to report', '보고서 본문으로'],
  language: ['报告语言', 'Report language', '보고서 언어'],
  intro: ['20 名候选，5 个位置。先看技术特点，再判断证据是否足够。', '20 candidates. Five positions. Understand each profile, then weigh the evidence.', '20명의 후보, 5개 포지션. 선수의 특징을 먼저 파악하고 근거의 충분성을 확인하세요.'],
  eventScope: ['仅比较本届同位置选手；不是职业水平或签约成功率评估。', 'Comparisons are within this event and position—not estimates of professional readiness or signing success.', '이번 대회 같은 포지션 내 비교입니다. 프로 수준이나 영입 성공률을 뜻하지 않습니다.'],
  realMatches: ['有效比赛', 'Played series', '실제 경기'],
  realMaps: ['统计地图', 'Recorded maps', '기록된 맵'],
  referencePlayers: ['完整比较池', 'Reference pool', '전체 비교 대상'],
  overviewTitle: ['五位置候选总览', 'Five-position scouting overview', '5개 포지션 후보 개요'],
  overviewSubtitle: ['每个位置保留 4 名候选；总分之外，优势和观察项一起看。', 'Four candidates per position, with strengths and open questions alongside the score.', '포지션별 후보 4명. 점수와 함께 강점과 확인할 점을 살펴봅니다.'],
  positionCta: ['查看{role}分析', 'Explore {role}', '{role} 분석 보기'],
  selectionNote: ['本轮模型候选 · 名单待确认', 'Model shortlist · pending confirmation', '모델 후보 명단 · 확정 전'],
  previewNote: ['V30 固定数据 · 2026.08.31 · 模型 v0.1 / 修订 3', 'Fixed V30 snapshot · 31 Aug 2026 · Model v0.1 / revision 3', 'V30 고정 데이터 · 2026.08.31 · 모델 v0.1 / 수정 3'],
  conclusion: ['经理视图', 'Manager view', '매니저 보기'],
  analysis: ['教练视图', 'Coach view', '코치 보기'],
  readingDepth: ['阅读深度', 'Reading depth', '읽기 방식'],
  positionTitle: ['{role} · 候选技术评估', '{role} · Candidate assessment', '{role} · 후보 기술 평가'],
  poolCaption: ['展示 4 人 / 同位置合格池 {total} 人', '4 shown / {total} eligible in this position', '표시 4명 / 해당 포지션 비교 대상 {total}명'],
  playerPoolCaption: ['本位置模型顺位 {rank} / {total}', 'Model rank {rank} / {total} in this position', '포지션 내 모델 순위 {rank} / {total}'],
  technicalIndex: ['技术指数', 'Technical index', '기술 지수'],
  indexMeaning: ['本位置 · /100', 'Within position · /100', '포지션 내 · /100'],
  rankLegend: ['按本位置技术指数排序，不是固定名单层级。', 'Ordered by the position index, not permanent shortlist tiers.', '포지션 기술 지수 순서이며 고정 명단 등급이 아닙니다.'],
  candidates: ['本轮候选', 'Current candidates', '이번 후보'],
  advantage: ['值得关注', 'What stands out', '주목할 점'],
  watch: ['仍需观察', 'What needs checking', '확인할 점'],
  profile: ['查看选手档案', 'Open player dossier', '선수 분석 보기'],
  steady: ['删场检查均入围', 'Retained in every omission check', '모든 경기 제외 검토에서 포함'],
  sensitive: ['入围结果有波动', 'Shortlist changes in omission checks', '경기 제외 시 후보 변동'],
  retentionMeaning: ['每次移除一场比赛后重算名单，共 36 次；不是选手的出场次数。', 'The shortlist was refitted 36 times, omitting one series each time. This is not the player’s match count.', '경기를 하나씩 제외해 총 36회 명단을 다시 계산했습니다. 선수의 출전 횟수가 아닙니다.'],
  stageLabel: ['季后赛证据', 'Playoff evidence', '플레이오프 근거'],
  stage_COMPARABLE: ['满足重复比较条件', 'Repeated comparison available', '반복 비교 조건 충족'],
  stage_LIMITED_SAMPLE: ['有记录，重复样本不足', 'Recorded, but limited sample', '기록은 있으나 표본 부족'],
  stage_LIMITED_REFERENCE: ['有记录，同位置参考不足', 'Recorded, but too few peers', '기록은 있으나 비교 선수 부족'],
  stage_NOT_OBSERVED: ['本位置无季后赛记录', 'No playoff record in this position', '해당 포지션 플레이오프 기록 없음'],
  stageDesc_COMPARABLE: ['满足至少 2 场、6 图，且同位置至少 3 名可比选手的条件。它表示可以比较，不代表表现一定优秀。', 'At least 2 series, 6 maps and 3 eligible peers. Comparable evidence does not automatically mean strong performance.', '최소 2경기·6맵, 같은 포지션 비교 선수 3명 조건을 충족합니다. 비교 가능하다는 뜻이지 우수하다는 판정은 아닙니다.'],
  stageDesc_LIMITED_SAMPLE: ['本位置季后赛尚未达到 2 场、6 图；实际记录保留，但不称为反复验证。', 'Fewer than 2 series or 6 maps in this position. Actual records are retained, without claiming repeated validation.', '해당 포지션에서 2경기·6맵 조건을 충족하지 못했습니다. 실제 기록은 유지하되 반복 검증으로 해석하지 않습니다.'],
  stageDesc_LIMITED_REFERENCE: ['个人样本已达门槛，但同位置合格参考不足 3 人；不额外生成季后赛相对名次分。', 'The player meets the sample gate, but fewer than 3 peers qualify. No additional playoff-relative ranking is assigned.', '개인 표본은 충족했지만 비교 가능한 선수가 3명 미만입니다. 별도의 플레이오프 상대 순위 점수는 부여하지 않습니다.'],
  stageDesc_NOT_OBSERVED: ['没有这类记录不等于能力为零；目前不能判断其季后赛表现。', 'No record does not mean zero ability. Playoff performance is not established here.', '기록이 없다고 능력이 없는 것은 아닙니다. 현재 플레이오프 경기력을 판단할 근거가 없습니다.'],
  appearance: ['本位置出场', 'Position sample', '해당 포지션 표본'],
  shortMapNote: ['本选手有 {n} 张真实短图，仅计入原始统计，不计入阶段与环境校正。', 'Short maps kept in raw statistics only: {n}. They are excluded from stage and context adjustment.', '실제 짧은 맵 {n}개는 원시 통계에만 포함하고 단계·환경 보정에서는 제외합니다.'],
  maps: ['{n} 图', '{n} maps', '{n}맵'],
  series: ['{n} 场', '{n} series', '{n}경기'],
  minutes: ['{n} 分钟', '{n} minutes', '{n}분'],
  primaryHeroes: ['主要英雄记录', 'Main hero records', '주요 영웅 기록'],
  heroMeasure: ['按地图记录英雄计数，不是精确换英雄时长；单图使用不等于熟练度验证。', 'Heroes are counted from map records, not exact swap durations. A recorded appearance does not establish proficiency.', '맵 기록의 영웅 기준이며 정확한 교체 시간은 아닙니다. 출전 기록만으로 숙련도를 입증할 수는 없습니다.'],
  compareHeading: ['同位置数据对照', 'Same-position comparison', '같은 포지션 데이터 비교'],
  compareSubheading: ['每 10 分钟统计；基准始终来自完整合格池，不随展示人数改变。', 'Per 10 minutes. Benchmarks always use the full eligible pool, not just the displayed candidates.', '10분당 기록입니다. 기준은 화면의 후보 수가 아니라 전체 적격 비교 대상에서 계산합니다.'],
  comparisonCaution: ['原始统计未作英雄或环境校正；校正表现单独列出。消灭、治疗和阻挡量不能直接等同于战术执行质量。', 'Raw statistics are unadjusted; adjusted performance is shown separately. Eliminations, healing and mitigation do not directly measure tactical execution.', '원시 통계는 영웅·환경 보정 전 값이며 보정 경기력은 별도 표시합니다. 처치·치유·경감량이 전술 수행의 질을 직접 측정하지는 않습니다.'],
  player: ['选手', 'Player', '선수'],
  poolMedian: ['同位置中位数', 'Position median', '포지션 중앙값'],
  per10: ['每 10 分钟', 'Per 10 min', '10분당'],
  metric_dmg: ['伤害', 'Damage', '피해량'],
  metric_elim: ['消灭', 'Eliminations', '처치'],
  metric_dth: ['死亡 ↓', 'Deaths ↓', '죽음 ↓'],
  metric_ast: ['助攻', 'Assists', '도움'],
  metric_heal: ['治疗', 'Healing', '치유량'],
  metric_block: ['阻挡', 'Mitigation', '경감량'],
  lowerBetter: ['死亡越少，图形越向外。', 'Fewer deaths plot farther out.', '죽음이 적을수록 바깥쪽에 표시됩니다.'],
  radarTitle: ['数据轮廓', 'Statistical profile', '기록 프로필'],
  radarHint: ['越靠外，该项统计在同位置中越靠前；虚线是中位线。这里展示原始统计，未作环境校正，面积不是能力总分。', 'Farther out means a higher within-position statistical rank; dashed is the median. These are unadjusted statistics. Area is not an ability score.', '바깥쪽일수록 같은 포지션 내 기록 순위가 높습니다. 점선은 중앙선입니다. 환경 보정 전 통계이며 면적은 종합 능력 점수가 아닙니다.'],
  radarAccessible: ['{name} 的四项统计，与本位置中位线对照。具体数值见下方表格。', 'Four statistics for {name} against the position median. Exact values are in the table below.', '{name}의 네 가지 기록과 포지션 중앙선 비교. 정확한 값은 아래 표에 있습니다.'],
  yourPlayer: ['本选手', 'Player', '선수'],
  rankOf: ['第 {rank} / {total}', '{rank} of {total}', '{total}명 중 {rank}위'],
  metricRank: ['同位排名¹', 'Position rank¹', '포지션 내 순위¹'],
  metric: ['指标', 'Statistic', '항목'],
  metricRankNote: ['¹ 死亡按从少到多排列，其余按从多到少；统计量不是对沟通、开团或技能时机的测量。', '¹ Deaths are ordered low to high; other statistics high to low. These do not measure communication, engagement quality or ability timing.', '¹ 죽음은 적은 순, 나머지는 많은 순입니다. 의사소통·진입 판단·스킬 타이밍을 측정한 값은 아닙니다.'],
  boundaryTitle: ['末席，为什么还要比较？', 'Why keep the final spots open?', '마지막 자리는 왜 더 비교하나요?'],
  boundaryOpen: ['展开相邻候选对照', 'Compare nearby candidates', '인접 후보 비교 펼치기'],
  currentShortlist: ['本轮候选', 'Shortlisted', '현재 후보'],
  referenceOnly: ['对照候选', 'Comparison only', '비교 후보'],
  retainedCount: ['明确入围 {n}/{total} 次', 'Retained {n}/{total} times', '{total}회 중 {n}회 포함'],
  tieCount: ['另有 {n} 次边界并列', 'Plus {n} cutoff tie', '경계 동점 {n}회 별도'],
  noAutomatic: ['对照候选不计入当前 20 人；总分的小差距不等于实际能力差距。', 'Comparison candidates are outside the current 20. Small score gaps do not establish ability gaps.', '비교 후보는 현재 20명에 포함되지 않습니다. 작은 점수 차이가 실력 차이를 입증하지는 않습니다.'],
  evidenceTitle: ['两场值得对照的比赛', 'Two series worth comparing', '함께 볼 두 경기'],
  evidenceHint: ['优点与疑问都保留；链接打开比赛数据，不是录像评审结论。', 'Keep both positive and cautionary evidence. Links open match statistics, not video-review conclusions.', '긍정적 근거와 의문점을 함께 제시합니다. 링크는 경기 기록이며 영상 리뷰 결과가 아닙니다.'],
  matchCta: ['打开比赛数据', 'Open match statistics', '경기 데이터 열기'],
  group: ['小组赛', 'Group stage', '조별리그'],
  playoffs: ['季后赛', 'Playoffs', '플레이오프'],
  mapOrders: ['本位置图 {maps}', 'Position maps {maps}', '해당 포지션 맵 {maps}'],
  adjusted: ['校正表现指数', 'Adjusted performance index', '환경 보정 경기력 지수'],
  allMatches: ['展开全部 {n} 场记录', 'Show all {n} series', '전체 {n}경기 펼치기'],
  mapDetail: ['查看地图与英雄', 'Maps and heroes', '맵과 영웅 보기'],
  question: ['进一步评估时，先核对什么？', 'What should further evaluation check?', '추가 평가에서 먼저 확인할 점'],
  modelTitle: ['分数从哪里来？', 'Where does the score come from?', '점수는 어떻게 계산하나요?'],
  modelHint: ['六项指数按本位置权重合成。样本量单独呈现，不另加能力分。', 'Six indices use position-specific weights. Sample size is shown separately, not awarded as extra ability points.', '여섯 지수에 포지션별 가중치를 적용합니다. 표본 크기는 따로 표시하며 능력 가산점으로 넣지 않습니다.'],
  factor: ['评价维度', 'Dimension', '평가 차원'],
  factorIndex: ['维度指数', 'Dimension index', '차원 지수'],
  weight: ['权重', 'Weight', '가중치'],
  points: ['计入分数', 'Contribution', '반영 점수'],
  neutral: ['中性处理', 'Neutral treatment', '중립 처리'],
  factor_performance: ['基础表现', 'Base performance', '기본 경기력'],
  factor_opponentAdjusted: ['对手与环境校正', 'Opponent & context adjustment', '상대·환경 보정'],
  factor_profileFloor: ['较差地图表现', 'Lower-quartile map performance', '하위 사분위 맵 경기력'],
  factor_consistency: ['发挥稳定性', 'Performance consistency', '경기력 일관성'],
  factor_stageValidation: ['季后赛证据', 'Playoff evidence', '플레이오프 근거'],
  factor_versatility: ['英雄覆盖', 'Hero coverage', '영웅 활용 범위'],
  factorDesc_performance: ['本位置基础表现，在完整同位池内比较。', 'Base performance compared with the full eligible position pool.', '전체 적격 포지션 선수와 비교한 기본 경기력입니다.'],
  factorDesc_opponentAdjusted: ['对对手强度、英雄与阵容环境作保守校正；不能完全消除队伍差异。', 'Conservative adjustment for opponents, heroes and lineup context; team differences cannot be fully removed.', '상대·영웅·조합 환경을 보수적으로 보정하지만 팀 차이를 완전히 제거하지는 못합니다.'],
  factorDesc_profileFloor: ['校正后单图表现的加权下四分位，不是最差一场比赛。', 'The weighted lower quartile of adjusted map performance—not the worst series.', '보정한 맵 경기력의 가중 하위 사분위이며 최악의 경기 한 번을 뜻하지 않습니다.'],
  factorDesc_consistency: ['描述地图间表现波动，不等于高压决策或心理素质。', 'Variation between maps, not pressure decision-making or mental resilience.', '맵 간 경기력 변동이며 압박 상황 판단이나 정신력을 뜻하지 않습니다.'],
  factorDesc_stageValidation: ['季后赛表现与阶段变化分别判断资格；证据不足的部分留在中性值 50。', 'Playoff performance and stage change qualify independently. Unsupported components remain neutral at 50.', '플레이오프 경기력과 단계 간 변화를 따로 판단합니다. 근거가 부족한 부분은 중립값 50으로 유지합니다.'],
  factorDesc_versatility: ['按各英雄记录时长的分布计算，不是已验证英雄熟练度。', 'Distribution of recorded time across heroes, not verified proficiency.', '영웅별 기록 시간 분포이며 숙련도 검증 결과는 아닙니다.'],
  contextTitle: ['对手、阶段与不确定性', 'Opponents, stages & uncertainty', '상대·대회 단계·불확실성'],
  phaseCaution: ['阶段数字来自可用于校正的地图；两阶段样本不够时，不作“进步／退步”判断。', 'Stage values use maps eligible for adjustment. Limited samples do not support claims of improvement or decline.', '단계별 값은 보정에 사용할 수 있는 맵 기준입니다. 표본이 부족하면 향상·하락을 단정하지 않습니다.'],
  changeUnknown: ['阶段变化证据不足', 'Stage change is not established', '단계 간 변화 근거 부족'],
  changeObserved: ['可比较阶段变化', 'Stage change is comparable', '단계 간 변화 비교 가능'],
  interval: ['校正表现的 90% 估计区间', '90% interval for adjusted performance', '보정 경기력의 90% 추정 구간'],
  intervalHint: ['这不是上方技术指数的置信区间，也不是胜率；仅描述当前环境模型下的估计范围。', 'Not an interval for the technical index above, and not a win probability. It describes the current context-model estimate.', '위 기술 지수의 신뢰구간이나 승률이 아닙니다. 현재 환경 모델의 추정 범위를 나타냅니다.'],
  pressure: ['较强对手样本', 'Stronger-opponent sample', '상대적으로 강한 상대 표본'],
  pressureHint: ['按本届队伍强度识别，不等于职业级对手；少量样本只能作线索。', 'Identified by team strength within this event, not professional opposition. Small samples are only indicative.', '본 대회 팀 강도로 분류하며 프로 상대라는 뜻은 아닙니다. 작은 표본은 단서로만 봅니다.'],
  reviewTitle: ['换一组比赛，名单还稳吗？', 'Does the shortlist depend on one series?', '경기 하나가 명단을 바꾸나요?'],
  reviewResult: ['{n} / {total}', '{n} / {total}', '{n} / {total}'],
  reviewRank: ['重算后的同位顺位范围：{min}–{max}', 'Position rank across refits: {min}–{max}', '재계산한 포지션 순위 범위: {min}–{max}'],
  reviewHint: ['每次删去全赛事的一场比赛，重算全部因子；这项检查衡量名单对现有比赛的敏感程度，不预测下一场。', 'Each refit removes one event series and recalculates every factor. This measures sensitivity to existing matches, not future performance.', '대회 경기 하나를 제외하고 모든 요인을 다시 계산합니다. 기존 경기에 대한 민감도 검사이며 다음 경기 예측이 아닙니다.'],
  weightReview: ['权重扰动检查', 'Weight sensitivity check', '가중치 민감도 검사'],
  weightReviewHint: ['各项权重在原值 ±30% 内变化并归一，共 5,000 次。入围次数只属于这组模型条件，不是签约成功率。', 'Weights vary by ±30% and are renormalized over 5,000 trials. Retention belongs to these model conditions, not signing success.', '가중치를 ±30% 범위에서 바꾸고 정규화한 5,000회 검사입니다. 포함 횟수는 이 모델 조건의 결과이며 영입 성공률이 아닙니다.'],
  methodology: ['范围、口径与缺失信息', 'Scope, methods & missing evidence', '분석 범위·기준·누락 정보'],
  methodologyIntro: ['本轮固定使用 QGCS4 V30。所有技术指数只在本届同位置内解释。', 'This preview uses the fixed QGCS4 V30 snapshot. All technical indices are interpreted within this event and position.', '고정된 QGCS4 V30 데이터를 사용합니다. 기술 지수는 본 대회 같은 포지션 안에서만 해석합니다.'],
  methodSample: ['43 名合格选手是固定基准。大位置至少 12 图、120 分钟、4 场；具体位置至少 10 图、100 分钟、4 场。前台展示 4 人不改变基准。', 'The reference pool is fixed at 43 players. Broad-role gate: 12 maps, 120 minutes, 4 series; specific-position gate: 10 maps, 100 minutes, 4 series. Showing four does not change it.', '비교 대상은 43명으로 고정됩니다. 대분류 역할은 12맵·120분·4경기, 세부 포지션은 10맵·100분·4경기 이상입니다. 4명을 표시해도 기준은 바뀌지 않습니다.'],
  methodMaps: ['统计覆盖 36 场真实比赛、124 张地图；26 张判负等行政地图不算表现。2 张真实短图保留原始统计，但不进入默认环境校正。', '36 played series and 124 maps. 26 administrative maps are excluded. Two short played maps remain in raw statistics but not default context adjustment.', '실제 36경기·124맵을 사용하고 행정 처리 26맵은 제외합니다. 실제 짧은 맵 2개는 원시 통계에 유지하되 기본 환경 보정에서 제외합니다.'],
  methodOpponents: ['对手强度已纳入校正，但 4 个小组之间主要靠 7 场季后赛连接。跨组、跨队伍比较仍有不确定性；不能把校正当成完全公平的实验。', 'Opponent strength is adjusted, but four groups are linked mainly through seven playoff series. Cross-group and cross-team uncertainty remains; adjustment is not a controlled experiment.', '상대 강도를 보정했지만 4개 조는 주로 플레이오프 7경기로 연결됩니다. 조·팀 간 불확실성이 남아 있으며 보정을 완전히 공정한 실험으로 볼 수 없습니다.'],
  methodMissing: ['战网 ID 取自本届 V30 参赛记录，按选手编号关联；20 名候选的国籍由报告提供方补充确认。不按昵称关联其他赛事，联系方式不展示。没有人工录像标注，不推断沟通、指挥、终极技能时机或队伍化学反应。', 'BattleTags come from the V30 event records, matched by player ID. Nationalities of the 20 candidates are confirmed separately by the report provider. Names are not linked across events and contact details are not displayed. Without manual video annotation, communication, shotcalling, ultimate timing and team chemistry are not inferred.', '배틀태그는 본 대회 V30 참가 기록의 선수 ID로 연결했으며 후보 20명의 국적은 보고서 제공자가 별도로 확인했습니다. 닉네임으로 다른 대회와 연결하지 않으며 연락처는 표시하지 않습니다. 수동 영상 분석 없이 의사소통·오더·궁극기 타이밍·팀 호흡을 추론하지 않습니다.'],
  methodScore: ['顺位是本轮模型结果，不是固定名单层级。分数采用固定的位置权重；36 次删场与 5,000 次权重检查不是独立赛事预测回测。', 'Order reflects this model run, not a permanent shortlist tier. Position weights are fixed. Omission and weight checks are not out-of-event predictive validation.', '순서는 이번 모델 결과이며 고정 명단 등급이 아닙니다. 포지션 가중치는 고정됩니다. 경기 제외·가중치 검사는 별도 대회 예측 검증이 아닙니다.'],
  source: ['查看 V30 数据来源', 'View the V30 source', 'V30 데이터 출처 보기'],
  sourceCaution: ['比赛链接可能显示后续更新；本报告数字固定于 V30。', 'Match links may reflect later updates; report values remain fixed to V30.', '경기 링크에는 이후 변경이 반영될 수 있으나 보고서 수치는 V30으로 고정됩니다.'],
  battleTag: ['战网 ID', 'BattleTag', '배틀태그'],
  nationalityPending: ['国籍：待核对', 'Nationality: awaiting verification', '국적: 확인 대기'],
  nationalityMainland: ['国籍：中国大陆', 'Nationality: Mainland China', '국적: 중국 본토'],
  empty: ['未找到这个档案', 'Dossier not found', '분석 자료를 찾을 수 없습니다'],
  emptyHint: ['本轮预览只提供 20 名候选的独立档案。', 'This preview provides individual dossiers for the 20 shortlisted players.', '이 미리보기는 후보 20명의 개별 분석을 제공합니다.'],
  positionEmpty: ['未找到这个位置', 'Position not found', '포지션을 찾을 수 없습니다'],
  furtherReading: ['继续看同位置候选', 'More candidates in this position', '같은 포지션의 다른 후보'],
  summaryThreeTitle: ['读分数前，先记住三件事', 'Three things to keep in mind', '점수를 읽기 전에'],
  stableSummary: ['14 人在本轮 36 次删场检查中始终入围；其余 6 席仍有变化。', '14 players remain shortlisted in all 36 omission checks; six spots vary.', '14명은 36회 경기 제외 검사에서 모두 포함됐고, 나머지 6자리는 변동이 있습니다.'],
  evidenceSummary: ['入围稳定，不等于季后赛证据充分。两种判断分别展示。', 'Stable selection does not imply sufficient playoff evidence. Both are shown separately.', '명단 유지가 충분한 플레이오프 근거를 뜻하지는 않습니다. 두 판단을 분리해 표시합니다.'],
  supportSummary: ['群辅看生存、较差地图表现与波动；不能只凭伤害、治疗判断。', 'Main support evaluation also weighs survival, lower-quartile maps and variation—not just output totals.', '메인 서포트는 생존·하위 맵 경기력·변동도 봅니다. 피해량·치유량만으로 판단하지 않습니다.'],
  managerHint: ['先看候选差异、优势与风险；需要时再展开证据。', 'Start with candidate differences, strengths and risks. Open the evidence when needed.', '후보 차이·강점·위험을 먼저 보고 필요할 때 근거를 펼칩니다.'],
  coachHint: ['展开同位指标、阶段条件和具体比赛，结论与经理视图一致。', 'Inspect statistics, stage conditions and match evidence. Conclusions stay the same.', '동일한 결론을 바탕으로 지표·대회 단계·경기 근거를 확인합니다.'],
  reportVersion: ['报告版本', 'Report version', '보고서 버전'],
  reportVersionValue: ['QGCS4 Scouting v{version}', 'QGCS4 Scouting v{version}', 'QGCS4 Scouting v{version}'],
  snapshotLabel: ['数据范围', 'Data scope', '데이터 범위'],
  snapshotValue: ['V30 · 36 场真实比赛', 'V30 · 36 played series', 'V30 · 실제 36경기'],
  dossierCount: ['选手技术档案', 'Player dossiers', '선수 분석 자료'],
  positionsCount: ['独立分析位置', 'Positions assessed', '분석 포지션'],
  leaderLabel: ['当前模型首位', 'Current model leader', '현재 모델 1위'],
  leaderStage: ['首位季后赛记录', 'Leader’s playoff sample', '1위 선수 플레이오프 기록'],
  leaderRetained: ['首位删场后入围', 'Leader retained after omissions', '경기 제외 후 1위 선수 후보 유지'],
  leadGap: ['与次位模型分差', 'Index gap to second', '2위와의 지수 차이'],
  gapCaution: ['分差属于当前模型，不是实际能力差距或胜率。', 'The gap belongs to this model, not an ability gap or win probability.', '현재 모델의 점수 차이이며 실력 차이나 승률이 아닙니다.'],
  indexShort: ['指数', 'Index', '지수'],
  roleBrief: ['位置判断', 'Position brief', '포지션 판단'],
  rankShort: ['模型 #{rank}', 'Model #{rank}', '모델 {rank}위'],
  candidateDetails: ['四名候选的优势与观察项', 'Strengths and questions for all four', '후보 4명의 강점과 확인할 점'],
  compareTitle: ['同位置候选对比台', 'Same-position comparison', '같은 포지션 후보 비교'],
  jumpCompare: ['直接比较候选', 'Compare candidates', '후보 바로 비교'],
  compareIntro: ['选 2–3 人并排看。先比较具体差异，再进入个人档案。', 'Compare 2–3 candidates side by side, then open a dossier for the evidence.', '후보 2~3명을 나란히 비교한 뒤 개인 분석에서 근거를 확인합니다.'],
  compareSelect: ['选择对比选手', 'Choose candidates to compare', '비교할 선수 선택'],
  compareToggle: ['对比 {name}', 'Compare {name}', '{name} 비교'],
  compareCount: ['已选 {n} 人 · 最少 2 人，最多 3 人', '{n} selected · choose 2–3', '{n}명 선택 · 2~3명 비교'],
  compareFocus: ['对比重点', 'Evidence focus', '비교 항목'],
  focus_overall: ['综合比较', 'Overall profile', '종합 비교'],
  focus_consistency: ['发挥稳定性', 'Consistency', '경기력 안정성'],
  focus_pressure: ['强敌与阶段', 'Opponents & stages', '강한 상대·대회 단계'],
  focus_heroes: ['英雄与地图', 'Heroes & maps', '영웅·맵'],
  focusHint_overall: ['条形越长，该项原始统计在完整同位置池中越靠前；中线为中位数。死亡越少越靠前。', 'Longer bars mean a higher rank in the full position pool; the line marks the median. Fewer deaths rank higher.', '막대가 길수록 전체 포지션 내 원시 지표 순위가 높습니다. 중앙선은 중앙값이며 죽음은 적을수록 높습니다.'],
  focusHint_consistency: ['较差地图表现与波动分别比较，不能从稳定性推断心理素质或沟通能力。', 'Compare lower-quartile performance and consistency separately; neither measures mentality or communication.', '하위 맵 경기력과 변동을 따로 비교하며 정신력이나 의사소통 능력으로 해석하지 않습니다.'],
  focusHint_pressure: ['先看是否有足够比赛，再看表现；没有记录与表现较差是两回事。', 'Check the sample before judging performance. Missing evidence is not poor performance.', '경기력보다 표본을 먼저 확인합니다. 기록 부재는 낮은 경기력과 다릅니다.'],
  focusHint_heroes: ['比较实际英雄使用与地图覆盖；记录数量不代表已验证的战术适配。', 'Compare recorded hero usage and map coverage, not assumed tactical fit.', '실제 영웅 사용과 맵 기록을 비교하며 전술 적합성을 가정하지 않습니다.'],
  focusNoReweight: ['切换对比重点不改变技术指数或名单顺位。', 'Changing the focus does not change the index or shortlist order.', '비교 항목을 바꿔도 기술 지수와 명단 순위는 변하지 않습니다.'],
  candidateRead: ['两人各自的依据', 'Each candidate’s case', '후보별 판단 근거'],
  candidateReadMany: ['三人各自的依据', 'Each candidate’s case', '후보별 판단 근거'],
  poolRankPlain: ['同位置 {rank} / {total}', 'Position {rank} / {total}', '포지션 내 {rank} / {total}'],
  viewPressure: ['查看强敌与阶段证据', 'Inspect opponent & stage evidence', '상대·단계 근거 보기'],
  pressureLimited: ['样本不足，仅作线索', 'Limited sample; indicative only', '표본 부족 · 참고용'],
  stageMissingShort: ['暂无记录', 'Not recorded', '기록 없음'],
  mapCoverage: ['{n} 张不同地图', '{n} distinct maps', '서로 다른 맵 {n}개'],
  viewHeroMaps: ['查看英雄×地图记录', 'Inspect hero × map records', '영웅 × 맵 기록 보기'],
  heroMapTitle: ['英雄 × 地图出场记录', 'Hero × map appearances', '영웅 × 맵 출전 기록'],
  heroMapIntro: ['格子数字是该英雄在该地图的记录次数，不是胜率或能力分。点选有记录的格子可查看对应比赛。', 'Cells count recorded appearances, not win rates or ability scores. Select a populated cell to see its matches.', '칸의 숫자는 출전 기록 횟수이며 승률이나 능력 점수가 아닙니다. 기록이 있는 칸을 누르면 경기를 볼 수 있습니다.'],
  heroMapCaption: ['覆盖本位置 {n} 图 · — 表示没有记录', 'All {n} position maps · — means no record', '해당 포지션 {n}맵 · —는 기록 없음'],
  heroMapCell: ['{hero} · {map} · {n} 次记录', '{hero} · {map} · {n} appearances', '{hero} · {map} · {n}회 기록'],
  heroMapSelected: ['对应比赛', 'Matching series', '해당 경기'],
  mapLabel: ['地图', 'Map', '맵'],
  viewExactStats: ['查看精确数值与同位中位数', 'Exact values & position medians', '정확한 수치와 포지션 중앙값'],
  indexFactorUnit: ['同位置维度指数 · /100', 'Position factor index · /100', '포지션 요인 지수 · /100']
}

export const POSITION_COPY = {
  TANK: {
    name: ['坦克', 'Tank', '탱커'],
    headline: ['先看 suna、katsuragi', 'Start with suna and katsuragi', 'suna와 katsuragi부터'],
    summary: ['suna 的生存与季后赛记录突出；katsuragi 输出高，但季后赛回落需单看。', 'suna stands out in survival and playoffs. katsuragi brings high output, with a playoff drop to examine.', 'suna는 생존과 플레이오프 기록이 돋보입니다. katsuragi는 높은 화력을 보였지만 플레이오프 하락을 확인해야 합니다.'],
    boundary: ['末两席保留 Feather、EVER、小黄对照；目前的小分差不足以锁定名额。', 'Compare Feather, EVER and 小黄 for two remaining spots. Small gaps do not settle the choice.', '남은 두 자리는 Feather·EVER·小黄을 비교합니다. 작은 점수 차이로 확정하기 어렵습니다.']
  },
  HITSCAN: {
    name: ['长枪', 'Hitscan', '히트스캔'],
    headline: ['堃堃、Yunzb 并列评估', 'Evaluate 堃堃 and Yunzb together', '堃堃과 Yunzb를 함께 평가'],
    summary: ['堃堃伤害领先，Yunzb 数据更均衡；两人的英雄与出场结构不同。', '堃堃 leads damage; Yunzb has a more balanced profile. Their hero and appearance mixes differ.', '堃堃은 피해량, Yunzb는 균형 잡힌 기록이 강점입니다. 영웅과 출전 구성이 다릅니다.'],
    boundary: ['ONW 暂占末席，sa 保留英雄需求对照。长枪的季后赛横比参考人数不足。', 'ONW holds the fourth spot, with sa as a hero-fit comparison. Too few hitscan peers qualify for playoff-relative scoring.', '현재 네 번째 후보는 ONW이며 sa는 영웅 적합성 비교 대상입니다. 플레이오프 상대 점수에 필요한 히트스캔 표본이 부족합니다.']
  },
  FLEX_DPS: {
    name: ['自由人', 'Flex DPS', '플렉스 DPS'],
    headline: ['Moon1ightT 值得优先看', 'Prioritize a look at Moon1ightT', 'Moon1ightT를 우선 검토'],
    summary: ['输出与季后赛记录共同支持头部判断；鸡、鬼影提供不同英雄方向。', 'Output and playoff records support the lead. 鸡 and 鬼影 offer different hero profiles.', '화력과 플레이오프 기록이 상위 평가를 뒷받침합니다. 鸡와 鬼影은 다른 영웅 구성을 제공합니다.'],
    boundary: ['小歪暂占末席；唯一一场季后赛不能代表持续抗压能力，删场检查另有一次第四席并列。', '小歪 holds the fourth spot. One playoff series cannot establish sustained pressure performance; one omission check ties at the cutoff.', '小歪이 네 번째 후보입니다. 플레이오프 한 경기로 지속적인 압박 대응력을 판단할 수 없고, 경기 제외 검사에서 경계 동점도 한 번 있었습니다.']
  },
  MAIN_SUPPORT: {
    name: ['群辅', 'Main support', '메인 서포트'],
    shortName: ['群辅', 'Main sup.', '메인 서포트'],
    headline: ['henage、Flipped 差距很小', 'henage and Flipped are close', 'henage와 Flipped는 근접'],
    summary: ['两人仅差 0.6 指数分；生存、英雄使用和季后赛证据比先排高低更重要。', 'A 0.6-point gap. Survival, hero usage and playoff evidence matter more than declaring a winner.', '지수 차이는 0.6점입니다. 우열 확정보다 생존·영웅 사용·플레이오프 근거가 중요합니다.'],
    boundary: ['slipknot 数据有亮点但无季后赛；小五有三轮季后赛。保留两种证据结构，不只按治疗量定名额。', 'slipknot has statistical strengths but no playoffs; 小五 has three playoff rounds. Keep both evidence profiles in view.', 'slipknot은 기록이 좋지만 플레이오프가 없고, 小五는 세 라운드 기록이 있습니다. 치유량만으로 자리를 정하지 않습니다.']
  },
  FLEX_SUPPORT: {
    name: ['枪辅', 'Flex support', '플렉스 서포트'],
    shortName: ['枪辅', 'Flex sup.', '플렉스 서포트'],
    headline: ['小狗与 JUBE，各有依据', '小狗 and JUBE: distinct strengths', '小狗과 JUBE, 서로 다른 근거'],
    summary: ['小狗治疗、助攻突出；JUBE 有三轮季后赛。黄昏的雾子数据强，但证据限于小组赛。', '小狗 excels in healing and assists; JUBE has three playoff rounds. 黄昏’s strong Kiriko record is group-stage only.', '小狗은 치유와 도움, JUBE는 세 라운드 플레이오프 기록이 강점입니다. 黄昏의 좋은 키리코 기록은 조별리그에 한정됩니다.'],
    boundary: ['末席继续比较小水与吉赛尔：生存与赛程记录，对照进攻贡献与阶段回落。', 'Compare 小水 with 吉赛尔: survival and event coverage versus offensive output and a stage decline.', '마지막 자리는 小水과 吉赛尔을 비교합니다. 생존·대회 기록과 공격 기여·단계별 하락을 함께 봅니다.']
  }
}

export function localize(lines, lang) {
  return lines[{ zh: 0, en: 1, ko: 2 }[getLanguage(lang)]]
}

const EN_SINGULAR_COPY = {
  maps: '{n} map',
  mapCoverage: '{n} distinct map',
  heroMapCell: '{hero} · {map} · {n} appearance'
}

export function textFor(lang, key, values = {}) {
  const singular = getLanguage(lang) === 'en' && Number(values.n) === 1 ? EN_SINGULAR_COPY[key] : null
  const text = singular || localize(UI_COPY[key], lang)
  return text.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`))
}
