import { normalizeLocale } from '../../lib/locales.js'
const entries = {
  title: ['比赛提醒', 'Match reminders', '比賽提醒', '경기 알림'],
  description: ['选择与你有关的周赛、参赛和执勤邮件。', 'Choose emails for your weekly matches and assigned duties.', '選擇與你有關的週賽、參賽和執勤郵件。', '참가하는 주간 경기와 배정된 업무의 이메일을 설정하세요.'],
  master: ['开启比赛邮件提醒', 'Enable match emails', '開啟比賽郵件提醒', '경기 이메일 알림 켜기'],
  detail: ['发送到已验证的登录邮箱；同一场的多个角色合并提醒。', 'Sent to your verified sign-in email. Multiple roles in one match are combined.', '傳送到已驗證的登入信箱；同一場的多個角色合併提醒。', '인증된 로그인 이메일로 전송하며 한 경기의 여러 역할은 합쳐서 알립니다.'],
  schedule: ['赛程与排班变化', 'Schedule and assignment changes', '賽程與排班變化', '경기 일정 및 업무 변경'],
  scheduleDetail: ['安排公布、改期、取消，以及你的本场身份变化。', 'Published arrangements, rescheduling, cancellations and changes to your role.', '安排公布、改期、取消，以及你的本場身分變化。', '일정 발표, 시간 변경, 취소 및 본인의 역할 변경.'],
  hour: ['赛前一小时', 'One hour before the match', '賽前一小時', '경기 시작 1시간 전'],
  hourDetail: ['核对时间，提前准备到场。', 'Check the time and prepare to arrive.', '核對時間，提前準備到場。', '시간을 확인하고 참가를 준비하세요.'],
  room: ['比赛房开放', 'When the room opens', '比賽房開放', '경기방 개방 시'],
  roomDetail: ['按本场实际开放时间提醒，通常提前 30 分钟。', 'Uses the actual opening time, usually 30 minutes before the match.', '按本場實際開放時間提醒，通常提前 30 分鐘。', '실제 개방 시간을 따릅니다. 보통 경기 시작 30분 전입니다.'],
  optIn: ['默认关闭，由你主动开启。关闭后，尚未发送的比赛邮件也会停止。账号验证和找回密码邮件单独处理。', 'Off until you enable it. Turning it off stops pending match emails too. Verification and password recovery emails are separate.', '預設關閉，由你主動開啟。關閉後，尚未傳送的比賽郵件也會停止。帳號驗證和密碼重設郵件分開處理。', '직접 켜기 전에는 꺼져 있습니다. 끄면 대기 중인 경기 이메일도 중단됩니다. 계정 인증과 비밀번호 복구는 별도로 처리됩니다.'],
  scope: ['目前支持已公布的正式周赛。草稿排班和训练赛不会发送比赛提醒。', 'Supports published official weekly matches. Draft assignments and practice matches do not send reminders.', '目前支援已公布的正式週賽。草稿排班和訓練賽不會傳送提醒。', '발표된 공식 주간 경기를 지원합니다. 초안 배정과 연습 경기는 알림을 보내지 않습니다.'],
  unavailable: ['比赛邮件服务尚未启用。你仍可在我的空间查看比赛与待办。', 'Match email service is not enabled yet. Your matches and tasks remain in My Space.', '比賽郵件服務尚未啟用。你仍可在我的空間查看比賽與待辦。', '경기 이메일 서비스가 아직 활성화되지 않았습니다. 내 공간에서 경기와 할 일을 확인하세요.'],
  unverified: ['请先验证登录邮箱，再开启提醒或发送测试邮件。', 'Verify your email before enabling reminders or sending a test.', '請先驗證登入信箱，再開啟提醒或傳送測試郵件。', '알림을 켜거나 테스트 메일을 보내기 전에 이메일을 인증하세요.'],
  verify: ['验证邮箱', 'Verify email', '驗證信箱', '이메일 인증'],
  save: ['保存提醒设置', 'Save reminder settings', '儲存提醒設定', '알림 설정 저장'],
  saving: ['正在保存…', 'Saving…', '正在儲存…', '저장 중…'],
  saved: ['已保存，将应用到已有的未来比赛和后续安排。', 'Saved for existing upcoming matches and future arrangements.', '已儲存，將套用到已有的未來比賽和後續安排。', '기존 예정 경기와 이후 일정에 적용됩니다.'],
  test: ['发送测试邮件', 'Send test email', '傳送測試郵件', '테스트 이메일 보내기'],
  testing: ['正在申请…', 'Requesting…', '正在申請…', '요청 중…'],
  queued: ['测试邮件已排队，请稍后检查收件箱和垃圾邮件。五分钟内重复点击不会重复发送。', 'Test email queued. Check your inbox and spam folder shortly. Requests within five minutes do not send duplicates.', '測試郵件已排入佇列，請稍後檢查收件匣和垃圾郵件。五分鐘內重複點擊不會重複傳送。', '테스트 이메일이 대기열에 추가되었습니다. 받은편지함과 스팸함을 확인하세요. 5분 이내에는 중복 발송하지 않습니다.'],
  acceptedTest: ['测试邮件已提交邮件服务，请检查收件箱和垃圾邮件。', 'Test email submitted to the mail service. Check your inbox and spam folder.', '測試郵件已提交郵件服務，請檢查收件匣和垃圾郵件。', '테스트 이메일이 메일 서비스에 제출되었습니다. 수신함과 스팸함을 확인하세요.'],
  loadFailed: ['暂时无法读取提醒设置。', 'Could not load reminder settings.', '暫時無法讀取提醒設定。', '알림 설정을 불러오지 못했습니다.'],
  saveFailed: ['保存结果尚未确认，请重新读取后核对。', 'Saving is unconfirmed. Reload and check your settings.', '儲存結果尚未確認，請重新讀取後核對。', '저장이 확인되지 않았습니다. 다시 불러와 확인하세요.'],
  testFailed: ['测试邮件申请失败，请稍后重试。', 'Test request failed. Please try again.', '測試郵件申請失敗，請稍後重試。', '테스트 요청에 실패했습니다. 다시 시도하세요.'],
  conflict: ['设置已在其他页面更新，请重新读取后再修改。', 'Settings changed in another page. Reload before editing.', '設定已在其他頁面更新，請重新讀取後再修改。', '다른 페이지에서 설정이 변경되었습니다. 다시 불러온 후 수정하세요.'],
  retry: ['重新读取', 'Reload', '重新讀取', '다시 불러오기'],
  loading: ['正在读取提醒设置…', 'Loading reminder settings…', '正在讀取提醒設定…', '알림 설정을 불러오는 중…'],
  recent: ['最近的邮件提醒', 'Recent email reminders', '最近的郵件提醒', '최근 이메일 알림'],
  empty: ['还没有提醒记录。', 'No reminder records yet.', '還沒有提醒紀錄。', '아직 알림 기록이 없습니다.'],
  deliveryHint: ['“已提交邮件服务”不代表已经进入收件箱，请以实际收件为准。', '“Submitted to mail service” does not confirm inbox delivery. Check your mailbox.', '「已提交郵件服務」不代表已進入收件匣，請以實際收件為準。', '메일 서비스 제출은 수신함 도착을 보장하지 않습니다. 실제 수신함을 확인하세요.'],
  PENDING: ['等待发送', 'Queued', '等待傳送', '발송 대기'],
  SENDING: ['正在发送', 'Sending', '正在傳送', '발송 중'],
  ACCEPTED: ['已提交邮件服务', 'Submitted to mail service', '已提交郵件服務', '메일 서비스에 제출됨'],
  FAILED: ['发送失败', 'Failed', '傳送失敗', '실패'],
  SKIPPED: ['未发送', 'Not sent', '未傳送', '발송하지 않음'],
  CANCELLED: ['已取消', 'Cancelled', '已取消', '취소됨'],
  SCHEDULE: ['赛程与排班', 'Schedule and assignments', '賽程與排班', '일정 및 업무'],
  HOUR: ['赛前提醒', 'Before the match', '賽前提醒', '경기 전 알림'],
  ROOM: ['比赛房开放', 'Room opening', '比賽房開放', '경기방 개방'],
  REMOVED: ['人员安排调整', 'Assignment changed', '人員安排調整', '업무 배정 변경'],
  UNSCHEDULED: ['比赛时间待定', 'Time to be confirmed', '比賽時間待定', '시간 미정'],
  TEST: ['测试邮件', 'Test email', '測試郵件', '테스트 이메일'],
  on: ['邮件提醒已开启', 'Match emails enabled', '郵件提醒已開啟', '경기 이메일 켜짐'],
  off: ['邮件提醒未开启', 'Match emails off', '郵件提醒未開啟', '경기 이메일 꺼짐'],
  manage: ['管理提醒', 'Manage reminders', '管理提醒', '알림 관리'],
  enable: ['开启邮件提醒', 'Enable match emails', '開啟郵件提醒', '경기 이메일 켜기'],
  next: ['距离开赛', 'Starts in', '距離開賽', '시작까지'],
  minutes: ['分钟', 'min', '分鐘', '분'],
  hours: ['小时', 'hr', '小時', '시간'],
  live: ['已到预定开赛时间', 'Scheduled start time reached', '已到預定開賽時間', '예정 시작 시간이 되었습니다'],
  openAt: ['比赛房开放于', 'Room opens', '比賽房開放於', '경기방 개방'],
  readonly: ['当前账号仅可查看提醒设置。', 'This account can only view reminder settings.', '目前帳號僅可查看提醒設定。', '이 계정은 알림 설정을 보기만 할 수 있습니다.'],
}
export function reminderCopy(locale) {
  const index = ['zh-CN', 'en-US', 'zh-TW', 'ko-KR'].indexOf(normalizeLocale(locale))
  return Object.fromEntries(Object.entries(entries).map(([key, values]) => [key, values[Math.max(0, index)]]))
}
export const reminderTime = (value, locale) => value && Number.isFinite(new Date(value).getTime()) ? new Intl.DateTimeFormat(normalizeLocale(locale), { timeZone: 'Asia/Shanghai', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)) : '—'
