// ISO 3166-1 country/territory codes; geographic grouping: UN M49, checked 2026-10-01.
// https://www.iso.org/iso-3166-country-codes.html
// https://unstats.un.org/unsd/methodology/m49/overview/
// 249 ISO codes + legacy XK (Kosovo). Names: existing project labels / Unicode CLDR.
export const REGION_GROUPS = [
  {
    value: "ASIA_EAST_SE",
    zh: "东亚 / 东南亚",
    tw: "東亞 / 東南亞",
    en: "East / Southeast Asia",
    ko: "동아시아 / 동남아시아",
    options: [
      {"value":"CN","zh":"中国大陆","tw":"中國大陸","en":"Mainland China","ko":"중국 본토"},
      {"value":"HK","zh":"中国香港","tw":"中國香港","en":"Hong Kong","ko":"홍콩(중국 특별행정구)"},
      {"value":"MO","zh":"中国澳门","tw":"中國澳門","en":"Macau","ko":"마카오(중국 특별행정구)"},
      {"value":"TW","zh":"中国台湾","tw":"中國臺灣","en":"Taiwan","ko":"대만"},
      {"value":"JP","zh":"日本","tw":"日本","en":"Japan","ko":"일본"},
      {"value":"KR","zh":"韩国","tw":"韓國","en":"South Korea","ko":"대한민국"},
      {"value":"KP","zh":"朝鲜","tw":"朝鮮","en":"North Korea","ko":"북한"},
      {"value":"MN","zh":"蒙古","tw":"蒙古","en":"Mongolia","ko":"몽골"},
      {"value":"BN","zh":"文莱","tw":"文萊","en":"Brunei","ko":"브루나이"},
      {"value":"KH","zh":"柬埔寨","tw":"柬埔寨","en":"Cambodia","ko":"캄보디아"},
      {"value":"ID","zh":"印度尼西亚","tw":"印度尼西亞","en":"Indonesia","ko":"인도네시아"},
      {"value":"LA","zh":"老挝","tw":"老撾","en":"Laos","ko":"라오스"},
      {"value":"MY","zh":"马来西亚","tw":"馬來西亞","en":"Malaysia","ko":"말레이시아"},
      {"value":"MM","zh":"缅甸","tw":"緬甸","en":"Myanmar","ko":"미얀마"},
      {"value":"PH","zh":"菲律宾","tw":"菲律賓","en":"Philippines","ko":"필리핀"},
      {"value":"SG","zh":"新加坡","tw":"新加坡","en":"Singapore","ko":"싱가포르"},
      {"value":"TH","zh":"泰国","tw":"泰國","en":"Thailand","ko":"태국"},
      {"value":"TL","zh":"东帝汶","tw":"東帝汶","en":"Timor-Leste","ko":"동티모르"},
      {"value":"VN","zh":"越南","tw":"越南","en":"Vietnam","ko":"베트남"}
    ]
  },
  {
    value: "ASIA_OTHER",
    zh: "亚洲其他地区",
    tw: "亞洲其他地區",
    en: "Rest of Asia",
    ko: "기타 아시아",
    options: [
      {"value":"AF","zh":"阿富汗","tw":"阿富汗","en":"Afghanistan","ko":"아프가니스탄"},
      {"value":"AM","zh":"亚美尼亚","tw":"亞美尼亞","en":"Armenia","ko":"아르메니아"},
      {"value":"AZ","zh":"阿塞拜疆","tw":"阿塞拜疆","en":"Azerbaijan","ko":"아제르바이잔"},
      {"value":"BH","zh":"巴林","tw":"巴林","en":"Bahrain","ko":"바레인"},
      {"value":"BD","zh":"孟加拉国","tw":"孟加拉國","en":"Bangladesh","ko":"방글라데시"},
      {"value":"BT","zh":"不丹","tw":"不丹","en":"Bhutan","ko":"부탄"},
      {"value":"CY","zh":"塞浦路斯","tw":"塞浦路斯","en":"Cyprus","ko":"키프로스"},
      {"value":"GE","zh":"格鲁吉亚","tw":"格魯吉亞","en":"Georgia","ko":"조지아"},
      {"value":"IN","zh":"印度","tw":"印度","en":"India","ko":"인도"},
      {"value":"IR","zh":"伊朗","tw":"伊朗","en":"Iran","ko":"이란"},
      {"value":"IQ","zh":"伊拉克","tw":"伊拉克","en":"Iraq","ko":"이라크"},
      {"value":"IL","zh":"以色列","tw":"以色列","en":"Israel","ko":"이스라엘"},
      {"value":"JO","zh":"约旦","tw":"約旦","en":"Jordan","ko":"요르단"},
      {"value":"KZ","zh":"哈萨克斯坦","tw":"哈薩克斯坦","en":"Kazakhstan","ko":"카자흐스탄"},
      {"value":"KW","zh":"科威特","tw":"科威特","en":"Kuwait","ko":"쿠웨이트"},
      {"value":"KG","zh":"吉尔吉斯斯坦","tw":"吉爾吉斯斯坦","en":"Kyrgyzstan","ko":"키르기스스탄"},
      {"value":"LB","zh":"黎巴嫩","tw":"黎巴嫩","en":"Lebanon","ko":"레바논"},
      {"value":"MV","zh":"马尔代夫","tw":"馬爾代夫","en":"Maldives","ko":"몰디브"},
      {"value":"NP","zh":"尼泊尔","tw":"尼泊爾","en":"Nepal","ko":"네팔"},
      {"value":"OM","zh":"阿曼","tw":"阿曼","en":"Oman","ko":"오만"},
      {"value":"PK","zh":"巴基斯坦","tw":"巴基斯坦","en":"Pakistan","ko":"파키스탄"},
      {"value":"PS","zh":"巴勒斯坦","tw":"巴勒斯坦","en":"Palestine","ko":"팔레스타인 지구"},
      {"value":"QA","zh":"卡塔尔","tw":"卡塔爾","en":"Qatar","ko":"카타르"},
      {"value":"SA","zh":"沙特阿拉伯","tw":"沙特阿拉伯","en":"Saudi Arabia","ko":"사우디아라비아"},
      {"value":"LK","zh":"斯里兰卡","tw":"斯里蘭卡","en":"Sri Lanka","ko":"스리랑카"},
      {"value":"SY","zh":"叙利亚","tw":"敘利亞","en":"Syria","ko":"시리아"},
      {"value":"TJ","zh":"塔吉克斯坦","tw":"塔吉克斯坦","en":"Tajikistan","ko":"타지키스탄"},
      {"value":"TR","zh":"土耳其","tw":"土耳其","en":"Turkey","ko":"튀르키예"},
      {"value":"TM","zh":"土库曼斯坦","tw":"土庫曼斯坦","en":"Turkmenistan","ko":"투르크메니스탄"},
      {"value":"AE","zh":"阿拉伯联合酋长国","tw":"阿拉伯聯合酋長國","en":"United Arab Emirates","ko":"아랍에미리트"},
      {"value":"UZ","zh":"乌兹别克斯坦","tw":"烏茲別克斯坦","en":"Uzbekistan","ko":"우즈베키스탄"},
      {"value":"YE","zh":"也门","tw":"也門","en":"Yemen","ko":"예멘"}
    ]
  },
  {
    value: "EUROPE",
    zh: "欧洲",
    tw: "歐洲",
    en: "Europe",
    ko: "유럽",
    options: [
      {"value":"AL","zh":"阿尔巴尼亚","tw":"阿爾巴尼亞","en":"Albania","ko":"알바니아"},
      {"value":"AD","zh":"安道尔","tw":"安道爾","en":"Andorra","ko":"안도라"},
      {"value":"AT","zh":"奥地利","tw":"奧地利","en":"Austria","ko":"오스트리아"},
      {"value":"BY","zh":"白俄罗斯","tw":"白俄羅斯","en":"Belarus","ko":"벨라루스"},
      {"value":"BE","zh":"比利时","tw":"比利時","en":"Belgium","ko":"벨기에"},
      {"value":"BA","zh":"波斯尼亚和黑塞哥维那","tw":"波斯尼亞和黑塞哥維那","en":"Bosnia and Herzegovina","ko":"보스니아 헤르체고비나"},
      {"value":"BG","zh":"保加利亚","tw":"保加利亞","en":"Bulgaria","ko":"불가리아"},
      {"value":"HR","zh":"克罗地亚","tw":"克羅地亞","en":"Croatia","ko":"크로아티아"},
      {"value":"CZ","zh":"捷克","tw":"捷克","en":"Czechia","ko":"체코"},
      {"value":"DK","zh":"丹麦","tw":"丹麥","en":"Denmark","ko":"덴마크"},
      {"value":"EE","zh":"爱沙尼亚","tw":"愛沙尼亞","en":"Estonia","ko":"에스토니아"},
      {"value":"FI","zh":"芬兰","tw":"芬蘭","en":"Finland","ko":"핀란드"},
      {"value":"FR","zh":"法国","tw":"法國","en":"France","ko":"프랑스"},
      {"value":"DE","zh":"德国","tw":"德國","en":"Germany","ko":"독일"},
      {"value":"GR","zh":"希腊","tw":"希臘","en":"Greece","ko":"그리스"},
      {"value":"HU","zh":"匈牙利","tw":"匈牙利","en":"Hungary","ko":"헝가리"},
      {"value":"IS","zh":"冰岛","tw":"冰島","en":"Iceland","ko":"아이슬란드"},
      {"value":"IE","zh":"爱尔兰","tw":"愛爾蘭","en":"Ireland","ko":"아일랜드"},
      {"value":"IT","zh":"意大利","tw":"意大利","en":"Italy","ko":"이탈리아"},
      {"value":"XK","zh":"科索沃","tw":"科索沃","en":"Kosovo","ko":"코소보"},
      {"value":"LV","zh":"拉脱维亚","tw":"拉脫維亞","en":"Latvia","ko":"라트비아"},
      {"value":"LI","zh":"列支敦士登","tw":"列支敦士登","en":"Liechtenstein","ko":"리히텐슈타인"},
      {"value":"LT","zh":"立陶宛","tw":"立陶宛","en":"Lithuania","ko":"리투아니아"},
      {"value":"LU","zh":"卢森堡","tw":"盧森堡","en":"Luxembourg","ko":"룩셈부르크"},
      {"value":"MT","zh":"马耳他","tw":"馬耳他","en":"Malta","ko":"몰타"},
      {"value":"MD","zh":"摩尔多瓦","tw":"摩爾多瓦","en":"Moldova","ko":"몰도바"},
      {"value":"MC","zh":"摩纳哥","tw":"摩納哥","en":"Monaco","ko":"모나코"},
      {"value":"ME","zh":"黑山","tw":"黑山","en":"Montenegro","ko":"몬테네그로"},
      {"value":"NL","zh":"荷兰","tw":"荷蘭","en":"Netherlands","ko":"네덜란드"},
      {"value":"MK","zh":"北马其顿","tw":"北馬其頓","en":"North Macedonia","ko":"북마케도니아"},
      {"value":"NO","zh":"挪威","tw":"挪威","en":"Norway","ko":"노르웨이"},
      {"value":"PL","zh":"波兰","tw":"波蘭","en":"Poland","ko":"폴란드"},
      {"value":"PT","zh":"葡萄牙","tw":"葡萄牙","en":"Portugal","ko":"포르투갈"},
      {"value":"RO","zh":"罗马尼亚","tw":"羅馬尼亞","en":"Romania","ko":"루마니아"},
      {"value":"RU","zh":"俄罗斯","tw":"俄羅斯","en":"Russia","ko":"러시아"},
      {"value":"SM","zh":"圣马力诺","tw":"聖馬力諾","en":"San Marino","ko":"산마리노"},
      {"value":"RS","zh":"塞尔维亚","tw":"塞爾維亞","en":"Serbia","ko":"세르비아"},
      {"value":"SK","zh":"斯洛伐克","tw":"斯洛伐克","en":"Slovakia","ko":"슬로바키아"},
      {"value":"SI","zh":"斯洛文尼亚","tw":"斯洛文尼亞","en":"Slovenia","ko":"슬로베니아"},
      {"value":"ES","zh":"西班牙","tw":"西班牙","en":"Spain","ko":"스페인"},
      {"value":"SE","zh":"瑞典","tw":"瑞典","en":"Sweden","ko":"스웨덴"},
      {"value":"CH","zh":"瑞士","tw":"瑞士","en":"Switzerland","ko":"스위스"},
      {"value":"UA","zh":"乌克兰","tw":"烏克蘭","en":"Ukraine","ko":"우크라이나"},
      {"value":"GB","zh":"英国","tw":"英國","en":"United Kingdom","ko":"영국"},
      {"value":"VA","zh":"梵蒂冈","tw":"梵蒂岡","en":"Vatican City","ko":"바티칸 시국"},
      {"value":"AX","zh":"奥兰群岛","tw":"奧蘭群島","en":"Åland Islands","ko":"올란드 제도"},
      {"value":"FO","zh":"法罗群岛","tw":"法羅群島","en":"Faroe Islands","ko":"페로 제도"},
      {"value":"GI","zh":"直布罗陀","tw":"直布羅陀","en":"Gibraltar","ko":"지브롤터"},
      {"value":"GG","zh":"根西岛","tw":"根息","en":"Guernsey","ko":"건지"},
      {"value":"IM","zh":"马恩岛","tw":"曼島","en":"Isle of Man","ko":"맨섬"},
      {"value":"JE","zh":"泽西岛","tw":"澤西島","en":"Jersey","ko":"저지"},
      {"value":"SJ","zh":"斯瓦尔巴和扬马延","tw":"挪威屬斯瓦巴及尖棉","en":"Svalbard & Jan Mayen","ko":"스발바르제도-얀마웬섬"}
    ]
  },
  {
    value: "AFRICA",
    zh: "非洲",
    tw: "非洲",
    en: "Africa",
    ko: "아프리카",
    options: [
      {"value":"DZ","zh":"阿尔及利亚","tw":"阿爾及利亞","en":"Algeria","ko":"알제리"},
      {"value":"AO","zh":"安哥拉","tw":"安哥拉","en":"Angola","ko":"앙골라"},
      {"value":"BJ","zh":"贝宁","tw":"貝寧","en":"Benin","ko":"베냉"},
      {"value":"BW","zh":"博茨瓦纳","tw":"博茨瓦納","en":"Botswana","ko":"보츠와나"},
      {"value":"BF","zh":"布基纳法索","tw":"布基納法索","en":"Burkina Faso","ko":"부르키나파소"},
      {"value":"BI","zh":"布隆迪","tw":"布隆迪","en":"Burundi","ko":"부룬디"},
      {"value":"CV","zh":"佛得角","tw":"佛得角","en":"Cape Verde","ko":"카보베르데"},
      {"value":"CM","zh":"喀麦隆","tw":"喀麥隆","en":"Cameroon","ko":"카메룬"},
      {"value":"CF","zh":"中非共和国","tw":"中非共和國","en":"Central African Republic","ko":"중앙 아프리카 공화국"},
      {"value":"TD","zh":"乍得","tw":"乍得","en":"Chad","ko":"차드"},
      {"value":"KM","zh":"科摩罗","tw":"科摩羅","en":"Comoros","ko":"코모로"},
      {"value":"CG","zh":"刚果共和国","tw":"剛果共和國","en":"Congo","ko":"콩고-브라자빌"},
      {"value":"CD","zh":"刚果民主共和国","tw":"剛果民主共和國","en":"Congo (DRC)","ko":"콩고-킨샤사"},
      {"value":"CI","zh":"科特迪瓦","tw":"科特迪瓦","en":"Cote d’Ivoire","ko":"코트디부아르"},
      {"value":"DJ","zh":"吉布提","tw":"吉布提","en":"Djibouti","ko":"지부티"},
      {"value":"EG","zh":"埃及","tw":"埃及","en":"Egypt","ko":"이집트"},
      {"value":"GQ","zh":"赤道几内亚","tw":"赤道幾內亞","en":"Equatorial Guinea","ko":"적도 기니"},
      {"value":"ER","zh":"厄立特里亚","tw":"厄立特里亞","en":"Eritrea","ko":"에리트리아"},
      {"value":"SZ","zh":"斯威士兰","tw":"斯威士蘭","en":"Eswatini","ko":"에스와티니"},
      {"value":"ET","zh":"埃塞俄比亚","tw":"埃塞俄比亞","en":"Ethiopia","ko":"에티오피아"},
      {"value":"GA","zh":"加蓬","tw":"加蓬","en":"Gabon","ko":"가봉"},
      {"value":"GM","zh":"冈比亚","tw":"岡比亞","en":"Gambia","ko":"감비아"},
      {"value":"GH","zh":"加纳","tw":"加納","en":"Ghana","ko":"가나"},
      {"value":"GN","zh":"几内亚","tw":"幾內亞","en":"Guinea","ko":"기니"},
      {"value":"GW","zh":"几内亚比绍","tw":"幾內亞比紹","en":"Guinea-Bissau","ko":"기니비사우"},
      {"value":"KE","zh":"肯尼亚","tw":"肯尼亞","en":"Kenya","ko":"케냐"},
      {"value":"LS","zh":"莱索托","tw":"萊索托","en":"Lesotho","ko":"레소토"},
      {"value":"LR","zh":"利比里亚","tw":"利比里亞","en":"Liberia","ko":"라이베리아"},
      {"value":"LY","zh":"利比亚","tw":"利比亞","en":"Libya","ko":"리비아"},
      {"value":"MG","zh":"马达加斯加","tw":"馬達加斯加","en":"Madagascar","ko":"마다가스카르"},
      {"value":"MW","zh":"马拉维","tw":"馬拉維","en":"Malawi","ko":"말라위"},
      {"value":"ML","zh":"马里","tw":"馬裡","en":"Mali","ko":"말리"},
      {"value":"MR","zh":"毛里塔尼亚","tw":"毛里塔尼亞","en":"Mauritania","ko":"모리타니"},
      {"value":"MU","zh":"毛里求斯","tw":"毛里求斯","en":"Mauritius","ko":"모리셔스"},
      {"value":"MA","zh":"摩洛哥","tw":"摩洛哥","en":"Morocco","ko":"모로코"},
      {"value":"MZ","zh":"莫桑比克","tw":"莫桑比克","en":"Mozambique","ko":"모잠비크"},
      {"value":"NA","zh":"纳米比亚","tw":"納米比亞","en":"Namibia","ko":"나미비아"},
      {"value":"NE","zh":"尼日尔","tw":"尼日爾","en":"Niger","ko":"니제르"},
      {"value":"NG","zh":"尼日利亚","tw":"尼日利亞","en":"Nigeria","ko":"나이지리아"},
      {"value":"RW","zh":"卢旺达","tw":"盧旺達","en":"Rwanda","ko":"르완다"},
      {"value":"ST","zh":"圣多美和普林西比","tw":"聖多美和普林西比","en":"Sao Tome and Principe","ko":"상투메 프린시페"},
      {"value":"SN","zh":"塞内加尔","tw":"塞內加爾","en":"Senegal","ko":"세네갈"},
      {"value":"SC","zh":"塞舌尔","tw":"塞舌爾","en":"Seychelles","ko":"세이셸"},
      {"value":"SL","zh":"塞拉利昂","tw":"塞拉利昂","en":"Sierra Leone","ko":"시에라리온"},
      {"value":"SO","zh":"索马里","tw":"索馬里","en":"Somalia","ko":"소말리아"},
      {"value":"ZA","zh":"南非","tw":"南非","en":"South Africa","ko":"남아프리카"},
      {"value":"SS","zh":"南苏丹","tw":"南蘇丹","en":"South Sudan","ko":"남수단"},
      {"value":"SD","zh":"苏丹","tw":"蘇丹","en":"Sudan","ko":"수단"},
      {"value":"TZ","zh":"坦桑尼亚","tw":"坦桑尼亞","en":"Tanzania","ko":"탄자니아"},
      {"value":"TG","zh":"多哥","tw":"多哥","en":"Togo","ko":"토고"},
      {"value":"TN","zh":"突尼斯","tw":"突尼斯","en":"Tunisia","ko":"튀니지"},
      {"value":"UG","zh":"乌干达","tw":"烏干達","en":"Uganda","ko":"우간다"},
      {"value":"ZM","zh":"赞比亚","tw":"贊比亞","en":"Zambia","ko":"잠비아"},
      {"value":"ZW","zh":"津巴布韦","tw":"津巴布韋","en":"Zimbabwe","ko":"짐바브웨"},
      {"value":"IO","zh":"英属印度洋领地","tw":"英屬印度洋領地","en":"British Indian Ocean Territory","ko":"영국령 인도양 지역"},
      {"value":"TF","zh":"法属南部领地","tw":"法屬南部屬地","en":"French Southern Territories","ko":"프랑스령 남방 지역"},
      {"value":"YT","zh":"马约特","tw":"馬約特島","en":"Mayotte","ko":"마요트"},
      {"value":"RE","zh":"留尼汪","tw":"留尼旺","en":"Réunion","ko":"레위니옹"},
      {"value":"SH","zh":"圣赫勒拿","tw":"聖赫勒拿島","en":"St. Helena","ko":"세인트헬레나"},
      {"value":"EH","zh":"西撒哈拉","tw":"西撒哈拉","en":"Western Sahara","ko":"서사하라"}
    ]
  },
  {
    value: "AMERICAS",
    zh: "美洲",
    tw: "美洲",
    en: "Americas",
    ko: "아메리카",
    options: [
      {"value":"AG","zh":"安提瓜和巴布达","tw":"安提瓜和巴布達","en":"Antigua and Barbuda","ko":"앤티가 바부다"},
      {"value":"AR","zh":"阿根廷","tw":"阿根廷","en":"Argentina","ko":"아르헨티나"},
      {"value":"BS","zh":"巴哈马","tw":"巴哈馬","en":"Bahamas","ko":"바하마"},
      {"value":"BB","zh":"巴巴多斯","tw":"巴巴多斯","en":"Barbados","ko":"바베이도스"},
      {"value":"BZ","zh":"伯利兹","tw":"伯利茲","en":"Belize","ko":"벨리즈"},
      {"value":"BO","zh":"玻利维亚","tw":"玻利維亞","en":"Bolivia","ko":"볼리비아"},
      {"value":"BR","zh":"巴西","tw":"巴西","en":"Brazil","ko":"브라질"},
      {"value":"CA","zh":"加拿大","tw":"加拿大","en":"Canada","ko":"캐나다"},
      {"value":"CL","zh":"智利","tw":"智利","en":"Chile","ko":"칠레"},
      {"value":"CO","zh":"哥伦比亚","tw":"哥倫比亞","en":"Colombia","ko":"콜롬비아"},
      {"value":"CR","zh":"哥斯达黎加","tw":"哥斯達黎加","en":"Costa Rica","ko":"코스타리카"},
      {"value":"CU","zh":"古巴","tw":"古巴","en":"Cuba","ko":"쿠바"},
      {"value":"DM","zh":"多米尼克","tw":"多米尼克","en":"Dominica","ko":"도미니카"},
      {"value":"DO","zh":"多米尼加共和国","tw":"多米尼加共和國","en":"Dominican Republic","ko":"도미니카 공화국"},
      {"value":"EC","zh":"厄瓜多尔","tw":"厄瓜多爾","en":"Ecuador","ko":"에콰도르"},
      {"value":"SV","zh":"萨尔瓦多","tw":"薩爾瓦多","en":"El Salvador","ko":"엘살바도르"},
      {"value":"GD","zh":"格林纳达","tw":"格林納達","en":"Grenada","ko":"그레나다"},
      {"value":"GT","zh":"危地马拉","tw":"危地馬拉","en":"Guatemala","ko":"과테말라"},
      {"value":"GY","zh":"圭亚那","tw":"圭亞那","en":"Guyana","ko":"가이아나"},
      {"value":"HT","zh":"海地","tw":"海地","en":"Haiti","ko":"아이티"},
      {"value":"HN","zh":"洪都拉斯","tw":"洪都拉斯","en":"Honduras","ko":"온두라스"},
      {"value":"JM","zh":"牙买加","tw":"牙買加","en":"Jamaica","ko":"자메이카"},
      {"value":"MX","zh":"墨西哥","tw":"墨西哥","en":"Mexico","ko":"멕시코"},
      {"value":"NI","zh":"尼加拉瓜","tw":"尼加拉瓜","en":"Nicaragua","ko":"니카라과"},
      {"value":"PA","zh":"巴拿马","tw":"巴拿馬","en":"Panama","ko":"파나마"},
      {"value":"PY","zh":"巴拉圭","tw":"巴拉圭","en":"Paraguay","ko":"파라과이"},
      {"value":"PE","zh":"秘鲁","tw":"秘魯","en":"Peru","ko":"페루"},
      {"value":"KN","zh":"圣基茨和尼维斯","tw":"聖基茨和尼維斯","en":"Saint Kitts and Nevis","ko":"세인트키츠 네비스"},
      {"value":"LC","zh":"圣卢西亚","tw":"聖盧西亞","en":"Saint Lucia","ko":"세인트루시아"},
      {"value":"VC","zh":"圣文森特和格林纳丁斯","tw":"聖文森特和格林納丁斯","en":"Saint Vincent and the Grenadines","ko":"세인트빈센트그레나딘"},
      {"value":"SR","zh":"苏里南","tw":"蘇里南","en":"Suriname","ko":"수리남"},
      {"value":"TT","zh":"特立尼达和多巴哥","tw":"特立尼達和多巴哥","en":"Trinidad and Tobago","ko":"트리니다드 토바고"},
      {"value":"US","zh":"美国","tw":"美國","en":"United States","ko":"미국"},
      {"value":"UY","zh":"乌拉圭","tw":"烏拉圭","en":"Uruguay","ko":"우루과이"},
      {"value":"VE","zh":"委内瑞拉","tw":"委內瑞拉","en":"Venezuela","ko":"베네수엘라"},
      {"value":"AI","zh":"安圭拉","tw":"安奎拉","en":"Anguilla","ko":"앵귈라"},
      {"value":"AW","zh":"阿鲁巴","tw":"荷屬阿魯巴","en":"Aruba","ko":"아루바"},
      {"value":"BM","zh":"百慕大","tw":"百慕達","en":"Bermuda","ko":"버뮤다"},
      {"value":"BQ","zh":"荷属加勒比区","tw":"荷蘭加勒比區","en":"Caribbean Netherlands","ko":"네덜란드령 카리브"},
      {"value":"BV","zh":"布韦岛","tw":"布威島","en":"Bouvet Island","ko":"부베섬"},
      {"value":"VG","zh":"英属维尔京群岛","tw":"英屬維京群島","en":"British Virgin Islands","ko":"영국령 버진아일랜드"},
      {"value":"KY","zh":"开曼群岛","tw":"開曼群島","en":"Cayman Islands","ko":"케이맨 제도"},
      {"value":"CW","zh":"库拉索","tw":"庫拉索","en":"Curaçao","ko":"퀴라소"},
      {"value":"FK","zh":"福克兰群岛","tw":"福克蘭群島","en":"Falkland Islands","ko":"포클랜드 제도"},
      {"value":"GF","zh":"法属圭亚那","tw":"法屬圭亞那","en":"French Guiana","ko":"프랑스령 기아나"},
      {"value":"GL","zh":"格陵兰","tw":"格陵蘭","en":"Greenland","ko":"그린란드"},
      {"value":"GP","zh":"瓜德罗普","tw":"瓜地洛普","en":"Guadeloupe","ko":"과들루프"},
      {"value":"MQ","zh":"马提尼克","tw":"馬丁尼克","en":"Martinique","ko":"마르티니크"},
      {"value":"MS","zh":"蒙特塞拉特","tw":"蒙哲臘","en":"Montserrat","ko":"몬트세라트"},
      {"value":"PR","zh":"波多黎各","tw":"波多黎各","en":"Puerto Rico","ko":"푸에르토리코"},
      {"value":"BL","zh":"圣巴泰勒米","tw":"聖巴瑟米","en":"St. Barthélemy","ko":"생바르텔레미"},
      {"value":"MF","zh":"法属圣马丁","tw":"法屬聖馬丁","en":"St. Martin","ko":"생마르탱"},
      {"value":"PM","zh":"圣皮埃尔和密克隆群岛","tw":"聖皮埃與密克隆群島","en":"St. Pierre & Miquelon","ko":"생피에르 미클롱"},
      {"value":"SX","zh":"荷属圣马丁","tw":"荷屬聖馬丁","en":"Sint Maarten","ko":"신트마르턴"},
      {"value":"GS","zh":"南乔治亚和南桑威奇群岛","tw":"南喬治亞與南三明治群島","en":"South Georgia & South Sandwich Islands","ko":"사우스조지아 사우스샌드위치 제도"},
      {"value":"TC","zh":"特克斯和凯科斯群岛","tw":"土克斯及開科斯群島","en":"Turks & Caicos Islands","ko":"터크스 케이커스 제도"},
      {"value":"VI","zh":"美属维尔京群岛","tw":"美屬維京群島","en":"U.S. Virgin Islands","ko":"미국령 버진아일랜드"}
    ]
  },
  {
    value: "OCEANIA",
    zh: "大洋洲",
    tw: "大洋洲",
    en: "Oceania",
    ko: "오세아니아",
    options: [
      {"value":"AU","zh":"澳大利亚","tw":"澳大利亞","en":"Australia","ko":"오스트레일리아"},
      {"value":"FJ","zh":"斐济","tw":"斐濟","en":"Fiji","ko":"피지"},
      {"value":"KI","zh":"基里巴斯","tw":"基里巴斯","en":"Kiribati","ko":"키리바시"},
      {"value":"MH","zh":"马绍尔群岛","tw":"馬紹爾群島","en":"Marshall Islands","ko":"마셜 제도"},
      {"value":"FM","zh":"密克罗尼西亚","tw":"密克羅尼西亞","en":"Micronesia","ko":"미크로네시아"},
      {"value":"NR","zh":"瑙鲁","tw":"瑙魯","en":"Nauru","ko":"나우루"},
      {"value":"NZ","zh":"新西兰","tw":"新西蘭","en":"New Zealand","ko":"뉴질랜드"},
      {"value":"PW","zh":"帕劳","tw":"帕勞","en":"Palau","ko":"팔라우"},
      {"value":"PG","zh":"巴布亚新几内亚","tw":"巴布亞新幾內亞","en":"Papua New Guinea","ko":"파푸아뉴기니"},
      {"value":"WS","zh":"萨摩亚","tw":"薩摩亞","en":"Samoa","ko":"사모아"},
      {"value":"SB","zh":"所罗门群岛","tw":"所羅門群島","en":"Solomon Islands","ko":"솔로몬 제도"},
      {"value":"TO","zh":"汤加","tw":"湯加","en":"Tonga","ko":"통가"},
      {"value":"TV","zh":"图瓦卢","tw":"圖瓦盧","en":"Tuvalu","ko":"투발루"},
      {"value":"VU","zh":"瓦努阿图","tw":"瓦努阿圖","en":"Vanuatu","ko":"바누아투"},
      {"value":"AS","zh":"美属萨摩亚","tw":"美屬薩摩亞","en":"American Samoa","ko":"아메리칸 사모아"},
      {"value":"CX","zh":"圣诞岛","tw":"聖誕島","en":"Christmas Island","ko":"크리스마스섬"},
      {"value":"CC","zh":"科科斯（基林）群岛","tw":"科克斯（基靈）群島","en":"Cocos (Keeling) Islands","ko":"코코스 제도"},
      {"value":"CK","zh":"库克群岛","tw":"庫克群島","en":"Cook Islands","ko":"쿡 제도"},
      {"value":"PF","zh":"法属波利尼西亚","tw":"法屬玻里尼西亞","en":"French Polynesia","ko":"프랑스령 폴리네시아"},
      {"value":"GU","zh":"关岛","tw":"關島","en":"Guam","ko":"괌"},
      {"value":"HM","zh":"赫德岛和麦克唐纳群岛","tw":"赫德島及麥唐納群島","en":"Heard & McDonald Islands","ko":"허드 맥도널드 제도"},
      {"value":"NC","zh":"新喀里多尼亚","tw":"新喀里多尼亞","en":"New Caledonia","ko":"뉴칼레도니아"},
      {"value":"NU","zh":"纽埃","tw":"紐埃島","en":"Niue","ko":"니우에"},
      {"value":"NF","zh":"诺福克岛","tw":"諾福克島","en":"Norfolk Island","ko":"노퍽섬"},
      {"value":"MP","zh":"北马里亚纳群岛","tw":"北馬利安納群島","en":"Northern Mariana Islands","ko":"북마리아나제도"},
      {"value":"PN","zh":"皮特凯恩群岛","tw":"皮特肯群島","en":"Pitcairn Islands","ko":"핏케언 제도"},
      {"value":"TK","zh":"托克劳","tw":"托克勞群島","en":"Tokelau","ko":"토켈라우"},
      {"value":"UM","zh":"美国本土外小岛屿","tw":"美國本土外小島嶼","en":"U.S. Outlying Islands","ko":"미국령 해외 제도"},
      {"value":"WF","zh":"瓦利斯和富图纳","tw":"瓦利斯群島和富圖那群島","en":"Wallis & Futuna","ko":"왈리스-푸투나 제도"}
    ]
  },
  {
    value: "ANTARCTIC",
    zh: "南极地区",
    tw: "南極地區",
    en: "Antarctic region",
    ko: "남극 지역",
    options: [
      {"value":"AQ","zh":"南极洲","tw":"南極洲","en":"Antarctica","ko":"남극 대륙"}
    ]
  },
  {
    value: "OTHER",
    zh: "其他 / 未列出",
    tw: "其他 / 未列出",
    en: "Other / Not listed",
    ko: "기타 / 목록에 없음",
    options: [
      {"value":"OTHER","zh":"其他 / 未列出地区","tw":"其他 / 未列出地區","en":"Other / Not listed","ko":"기타 / 목록에 없음"}
    ]
  }
]

export const DEFAULT_REGION_GROUP = REGION_GROUPS[0].value

export function getRegionGroup(value) {
  return REGION_GROUPS.find(group => group.value === value) || REGION_GROUPS[0]
}

export function getRegionOption(value) {
  for (const group of REGION_GROUPS) {
    const option = group.options.find(item => item.value === value)
    if (option) return option
  }
  if (value === 'OVERSEAS') return REGION_GROUPS.at(-1).options[0]
  return value ? { value, zh: value, tw: value, en: value, ko: value } : null
}

export function getRegionGroupValueForCode(value) {
  return REGION_GROUPS.find(group => group.options.some(option => option.value === value))?.value || DEFAULT_REGION_GROUP
}

export function getLocalizedOption(option, locale) {
  if (!option) return ''
  return locale === 'en-US' ? option.en : locale === 'zh-TW' ? option.tw || option.zh : locale === 'ko-KR' ? option.ko || option.en : option.zh
}
