import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const IMAGE_EXTENSIONS = new Set(['.png', '.webp', '.jpg', '.jpeg', '.svg'])
const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(scriptDirectory, '..')
const logosRoot = path.join(projectRoot, 'public', 'logos')
const outputPath = path.join(projectRoot, 'src', 'generated', 'teamLogoCatalog.js')

function normalizeKey(value) {
  return String(value || '')
    .normalize('NFKC')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toLocaleLowerCase('en-US')
    .replace(/[^\p{L}\p{N}]+/gu, '')
}

function logoUrl(directory, fileName) {
  return `/logos/${encodeURIComponent(directory)}/${encodeURIComponent(fileName)}`
}

function assignUnique(target, key, value, context) {
  if (!key) return
  if (target[key] && target[key] !== value) {
    throw new Error(`TEAM_LOGO_CATALOG_COLLISION: ${context} resolves to both ${target[key]} and ${value}`)
  }
  target[key] = value
}

function readAliases(directoryPath) {
  const aliasPath = path.join(directoryPath, 'team-logo-aliases.json')
  if (!fs.existsSync(aliasPath)) return {}
  const parsed = JSON.parse(fs.readFileSync(aliasPath, 'utf8'))
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`TEAM_LOGO_ALIASES_INVALID: ${aliasPath} must contain an object`)
  }
  return parsed
}

function buildDirectoryEntry(directoryName) {
  const directoryPath = path.join(logosRoot, directoryName)
  const files = fs.readdirSync(directoryPath, { withFileTypes: true })
    .filter(entry => entry.isFile() && IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase()))
    .map(entry => entry.name)
    .sort((a, b) => a.localeCompare(b, 'en'))
  const fileNames = new Set(files)
  const assets = {}

  files.forEach(fileName => {
    const stem = path.basename(fileName, path.extname(fileName))
    assignUnique(assets, normalizeKey(stem), logoUrl(directoryName, fileName), `${directoryName}/${stem}`)
  })

  const aliases = {}
  Object.entries(readAliases(directoryPath))
    .sort(([left], [right]) => left.localeCompare(right, 'en'))
    .forEach(([alias, fileName]) => {
      if (typeof fileName !== 'string' || !fileNames.has(fileName)) {
        throw new Error(`TEAM_LOGO_ALIAS_TARGET_MISSING: ${directoryName}/${alias} -> ${String(fileName)}`)
      }
      assignUnique(aliases, normalizeKey(alias), logoUrl(directoryName, fileName), `${directoryName}/${alias}`)
    })

  return {
    assets,
    aliases,
    fallback: assets[normalizeKey('OW')] || ''
  }
}

const catalog = {}
fs.readdirSync(logosRoot, { withFileTypes: true })
  .filter(entry => entry.isDirectory())
  .map(entry => entry.name)
  .sort((a, b) => a.localeCompare(b, 'en'))
  .forEach(directoryName => {
    catalog[directoryName] = buildDirectoryEntry(directoryName)
  })

const output = `// Generated by scripts/buildTeamLogoCatalog.mjs. Do not edit by hand.\nexport const TEAM_LOGO_CATALOG = Object.freeze(${JSON.stringify(catalog, null, 2)})\n`
fs.mkdirSync(path.dirname(outputPath), { recursive: true })
const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : ''
if (current !== output) fs.writeFileSync(outputPath, output, 'utf8')

const assetCount = Object.values(catalog).reduce((sum, entry) => sum + Object.keys(entry.assets).length, 0)
const aliasCount = Object.values(catalog).reduce((sum, entry) => sum + Object.keys(entry.aliases).length, 0)
console.log(`Team logo catalog: ${Object.keys(catalog).length} directories, ${assetCount} assets, ${aliasCount} aliases`)
