import { readFileSync, writeFileSync } from 'node:fs'

const directory = new URL('../src/locales/', import.meta.url)
const catalog = JSON.parse(readFileSync(new URL('ui.json', directory), 'utf8'))
for (const locale of ['zh-TW', 'ko-KR', 'en-US']) {
  const dictionary = Object.fromEntries(Object.entries(catalog)
    .filter(([, entry]) => typeof entry[locale] === 'string')
    .map(([source, entry]) => [source, entry[locale]]))
  writeFileSync(new URL(`${locale}.js`, directory), `// Generated by npm run build:locales from ui.json.\nexport default ${JSON.stringify(dictionary, null, 2)}\n`)
  console.log(`${locale}: ${Object.keys(dictionary).length} interface messages`)
}
